# Generated by Django 3.1.2 on 2020-12-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201210_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.category'),
        ),
    ]
