# Generated by Django 3.1.2 on 2020-12-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201210_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryName',
            new_name='categoryId',
        ),
    ]
